---
- hosts: dns
  tasks:
    - name: Ensure lighttpd-mod-openssl installed
      ansible.builtin.package:
        name: lighttpd-mod-openssl
        state: present
      register: out
    - debug: var=out.stdout_lines

    - name: ensure /etc/lighttpd/certs exists
      file:
        path: /etc/lighttpd/certs
        state: directory
        owner: root
        group: root
        mode: 0644
      register: out
    - debug: var=out.stdout_lines

    - name: create self signed cert
      command: >
        openssl req -x509 -nodes -subj '/CN={{ ansible_host }}' -days 365 -newkey rsa:4096 -sha256 -keyout /etc/lighttpd/certs/server.key -out /etc/lighttpd/certs/server.crt
        creates=/etc/lighttpd/certs/server.crt
      register: out
    - debug: var=out.stdout_lines

    - name: ensure lightttpd ssl config exists
      copy:
        src: lighttpd.conf
        dest: /etc/lighttpd/lighttpd.conf
        owner: root
        group: root
        mode: 0644
      register: out
    - debug: var=out.stdout_lines