---
- hosts: dns
  tasks:
    - name: ensure /etc/lighttpd/certs exists
      file:
        path: /etc/lighttpd/certs
        state: directory
        owner: root
        group: root
        mode: 0644
      register: out
    - debug: var=out.stdout_lines

    - name: create self signed cert
      command: >
        openssl req -new -x509 -keyout /etc/lighttpd/certs/lighttpd.pem -out /etc/lighttpd/certs/lighttpd.pem -days 365 -nodes
        creates=/etc/lighttpd/certs/lighttpd.pem
      register: out
    - debug: var=out.stdout_lines